FROM archlinux:base-@ARCH_VERSION@

RUN pacman-key --init
RUN pacman --noconfirm -Sy
RUN pacman --noconfirm -S archlinux-keyring
RUN pacman-key --populate
RUN pacman --noconfirm -Syyuu
RUN pacman --noconfirm -S @HOST_REQUIREMENTS@ @C15_REQUIREMENTS@

RUN mkdir -p /packages
RUN mkdir -p /tmp/blankdb
WORKDIR /packages
RUN pacman --noconfirm -Syw --cachedir . --dbpath /tmp/blankdb @C15_REQUIREMENTS@

RUN pacman --noconfirm -S npm nodejs rsync
RUN npm install -g typescript js-yaml @types/node @types/js-yaml
