#pragma once

class Preset;

class PresetAutoGeneratedAttributesLock {
public:
    PresetAutoGeneratedAttributesLock(Preset* p);
    ~PresetAutoGeneratedAttributesLock();
private:
    Preset* m_preset;
};
