ARG arch_version
FROM archlinux:${arch_version}
ARG packages
RUN echo "[dvzrv]" >> /etc/pacman.d/mirrorlist
RUN echo "Server = https://pkgbuild.com/~dvzrv/repo/\$arch" >> /etc/pacman.d/mirrorlist
RUN pacman --noconfirm -Syy
RUN pacman --noconfirm -S ${packages} arch-install-scripts dosfstools cmake make pkgconf gcc git wget unzip jdk11-openjdk fuse-overlayfs fuse3
