#pragma once

#include <serialization/Serializer.h>
#include <presets/PresetAutoGeneratedAttributesLock.h>

class Preset;

class PresetSerializer : public Serializer
{
 public:
  explicit PresetSerializer(Preset *preset, bool ignoreUUIDs = false);
  ~PresetSerializer() override;

  static Glib::ustring getTagName();

 private:
  void writeTagContent(Writer &writer) const override;
  void readTagContent(Reader &reader) const override;

  Preset *m_preset = nullptr;
  PresetAutoGeneratedAttributesLock m_presetLock;

  bool m_ignoreUUIDs = false;
};
