#include "PresetAutoGeneratedAttributesLock.h"
#include "presets/Preset.h"

PresetAutoGeneratedAttributesLock::PresetAutoGeneratedAttributesLock(Preset* p)
    : m_preset { p }
{
  m_preset->lockAutoGeneratedAttributes();
}
PresetAutoGeneratedAttributesLock::~PresetAutoGeneratedAttributesLock()
{
  m_preset->unlockAutoGeneratedAttributes();
}
