#pragma once

class Preset;

class PresetAutoGeneratedAttributesLock
{
 public:
  explicit PresetAutoGeneratedAttributesLock(Preset* p);
  ~PresetAutoGeneratedAttributesLock();

 private:
  Preset* m_preset;
};
