# fetches packages from NL server

SET(DOWNLOAD_BASE_URL http://${NL_SERVER}${NL_DOWNLOAD_PATH})

FOREACH(PACKAGE ${EPC2_PACKAGES})
    SEPARATE_ARGUMENTS(PACKAGE)
    LIST(GET PACKAGE 0 PACKAGE_NAME)
    LIST(GET PACKAGE 1 PACKAGE_VERSION)

    STRING(SHA512 SHA "${PACKAGE_NAME}-${PACKAGE_VERSION}")
    
    ADD_CUSTOM_COMMAND(
      OUTPUT ${DOWNLOAD_DIR}/stamps/${SHA}
      COMMAND mkdir -p ${DOWNLOAD_DIR}/stamps
      COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/fetch/download.sh ${DOWNLOAD_BASE_URL} ${PACKAGE_NAME} ${PACKAGE_VERSION} ${DOWNLOAD_DIR} ${SHA}
    )
    
    LIST(APPEND EPC2_DOWNLOADED_NL_FILES ${DOWNLOAD_DIR}/stamps/${SHA})
ENDFOREACH()

ADD_CUSTOM_TARGET(bt2-epc2-fetch-nl-resources DEPENDS ${EPC2_DOWNLOADED_NL_FILES})